config/routes.rb
Rails.application.routes.draw do

  root to: 'app#index'

  devise_scope :accountant do
    post '/accountants/sign_in', to: 'accountants/sessions#create'
    get '/accountants/sign_in', to: 'accountants/sessions#new'
    get '/accountants/sign_up', to: 'accountants/registrations#new'
    post '/accountants/', to: 'accountants/registrations#create'
  end


  devise_for :accountants
  # resources :transactions
  resources :subitems
  resources :items
  resources :accounts do
    get :line_chart, on: :collection
  end
  resources :accountants
  resources :debts
  resources :transfers do
    get :pie_chart, on: :collection
  end
  resources :bank_statements, only: [:new, :create]

  resources :reports, only: [] do
    get :line, on: :collection
    get :pie_chart, on: :collection
  end

  get '/reports', to: 'reports#transfers'

  namespace :admins do
    resources :tasks
  end

end

app/controllers/debts_controller.rb
class DebtsController < AuthenticateBaseController
  before_action :set_facade, only: [:index, :create, :update, :destroy]
  before_action :set_task, only: [:edit, :update, :destroy]
  
  def index
    task_all
  end
  
  def new
    @task = Task.new
  end
  
  def edit
  end
  
  def create

    debt = task_params
    debt[:done] = false
    debt[:task_type] = :debt
    @task = Task.new(debt)
  
    @task.accountant = current_accountant
  
    transporter = @facade.insert @task
  
    if transporter.status == :green
      flash[:notice] = 'Task criado.'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      render :new
    end
  end
  
  def update
  
    transporter = @facade.update @task, attributes: task_params
  
    if transporter.status == :green
      flash[:notice] = 'Task atualizado.!'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      render :edit
    end
  end
  
  def destroy
  
    transporter = @facade.delete @task
  
    if transporter.status == :green
      flash[:notice] = 'Tarefa deletada'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      redirect_to action: :index
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    if params[:task].present?
      params.require(:task).permit(:id, :name, :description, :due_date, :task_type, :done)
    else
      params.permit(:id, :name, :description)
    end
  end
  
  def task_all
    transporter = @facade.select(:task, task_type: :debt)
    @tasks = transporter.bucket[:tasks]
  end

  def set_facade
    @facade ||= Facade.new(current_accountant)
  end
  
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/views/debts/_form.html.haml
.row
  .col-lg-12
    %h3.page-header
      %i.fa.fa-laptop
      Contas a pagar
    %ol.breadcrumb{ style: 'background-color: gainsboro;' }
      %li
        %i.fa.fa-home
        %a{href: "/"} Home
      %li
        = link_to 'Debts', debts_path

%section.panel
  %header.panel-heading
    %h1= title
  .panel-body
    = form_with(model: task, url: url, method: method, local: true, class: 'form-horizontal') do |form|
      .form-group
        = form.label 'Nome', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :name, class: 'form-control'
      .form-group
        = form.label 'Descrição', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_area :description, class: 'form-control', column: 3
      .form-group
        = form.label 'Data de vencimento', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :due_date, value: due_date, class: 'form-control', type: :date
      - if params[:action] == 'edit'
        .form-group
          = form.label 'Pago', class: 'col-lg-2 control-label'
          .col-lg-10
            = form.check_box :done, value: :done
      .form-group
        .col-lg-offset-2.col-lg-10
          = form.submit button, class: 'btn btn-primary'

app/views/debts/edit.html.haml
= render 'form', task: @task, method: :put, title: 'ATUALIZAR TAREFA', button: 'Atualizar', due_date: @task.due_date, url: debt_path

app/views/debts/index.html.haml
.row
  .col-lg-12
    %h3.page-header
      %i.fa.fa-laptop
      Contas a pagar
    %ol.breadcrumb{ style: 'background-color: gainsboro;' }
      %li
        %i.fa.fa-home
        %a{href: "/"} Home
      %li= link_to 'Tarefa', debts_path
      %li= link_to 'Criar nova tarefa', new_debt_path

.row
  .col-lg-12
    %table#table-item.table.table-bordered
      %thead
        %tr{:role => "row"}
          %th Nome
          %th Descrição
          %th Data de pagamento
          %th Pago
          %th Ações
      %tbody
        - @tasks.each do |task|
          %tr.gradeA.odd{:role => "row", class: task.done ? 'done' : 'not-done' }
            %td= task.name
            %td= task.description
            %td= format_date task.due_date
            %td= task.done
            %td
              = link_to edit_debt_path(task), class: 'btn btn-warning' do
                editar
                %i.fas.fa-edit
              = link_to debt_path(task), method: :delete, class: 'btn btn-danger', data: { confirm: 'Você tem certeza?' } do
                excluir

app/views/debts/new.html.haml
= render 'form', task: @task, method: :post, title: 'NOVO TAREFA', button: 'Salvar', due_date: Date.today + 7.days, url: debts_path