config/routes.rb
Rails.application.routes.draw do

  root to: 'app#index'

  devise_scope :accountant do
    post '/accountants/sign_in', to: 'accountants/sessions#create'
    get '/accountants/sign_in', to: 'accountants/sessions#new'
    get '/accountants/sign_up', to: 'accountants/registrations#new'
    post '/accountants/', to: 'accountants/registrations#create'
  end


  devise_for :accountants
  # resources :transactions
  resources :subitems
  resources :items
  resources :accounts do
    get :line_chart, on: :collection
  end
  resources :accountants
  resources :debts
  resources :transfers do
    get :pie_chart, on: :collection
  end
  resources :bank_statements, only: [:new, :create]

  resources :reports, only: [] do
    get :line, on: :collection
    get :pie_chart, on: :collection
  end

  get '/reports', to: 'reports#transfers'

  namespace :admins do
    resources :tasks
  end

end

app/models/subitem.rb
# == Schema Information
#
# Table name: subitems
#
#  id           :bigint(8)        not null, primary key
#  account_type :string
#  description  :string
#  level        :string
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  item_id      :bigint(8)
#
# Indexes
#
#  index_subitems_on_item_id  (item_id)
#

class Subitem < ApplicationRecord
  extend RuleMap

  belongs_to :item

  rules_of_insert [
    Strategy::Subitems::CheckName,
    Strategy::SaveEntity,
  ]

  rules_of_update [
    Strategy::Subitems::CheckName,
    Strategy::SaveEntity,
  ]

  rules_of_destroy [
    Strategy::Subitems::CheckExistAssociationToSubitem,
    Strategy::DestroyEntity,
  ]

  rules_of_list [
    Strategy::Subitems::Filter,
  ]
end

app/controllers/subitems_controller.rb
class SubitemsController < AuthenticateBaseController
  before_action :set_subitem, only: [:edit, :update, :destroy]
  before_action :set_facade, only: [:index, :create, :update, :destroy]

  def index
    subitem_all
  end

  def new
    @subitem = Subitem.new
  end

  def edit
  end

  def create

    @subitem = Subitem.new(subitem_params)
    transporter = @facade.insert(@subitem)

    if transporter.status == :green
      flash[:notice] = 'Subitem criado com sucesso'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      render :new
    end
  end

  def update

    transporter = @facade.update @subitem, attributes: subitem_params

    if transporter.status == :green
      flash[:notice] = 'Subitem atualizado com sucesso!'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      render :edit
    end
  end

  def destroy
    transporter = @facade.delete @subitem

    if transporter.status == :green
      flash[:notice] = 'Subitem deletado com sucesso'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      render :index
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_subitem
    @subitem = Subitem.find(params[:id])
  end

  def subitem_params
    params.require(:subitem).permit(:name, :description, :level, :account_type, :item_id)
  end

  def subitem_all
    subitems = []
    current_accountant.items.each do |item|
      item.subitems.each do |subitem|
        subitems << subitem
      end
    end
    @subitems = subitems.sort_by { |sub| sub.name }
  end

  def set_facade
    @facade ||= Facade.new(current_accountant)
  end

end

app/helpers/subitems_helper.rb
module SubitemsHelper
end

app/views/subitems/_form.html.haml
.row
  .col-lg-12
    %h3.page-header
      %i.fa.fa-laptop
      Subitem
    %ol.breadcrumb{ style: 'background-color: gainsboro;' }
      %li
        %i.fa.fa-home
        %a{href: "/"} Home
      %li= link_to 'Subitem', subitems_path
      %li= link_to 'Criar subitem', new_subitem_path

%section.panel
  %header.panel-heading
    %h1= title
  .panel-body
    = form_with(model: subitem, method: method, local: true, class: 'form-horizontal') do |form|
      .form-group
        = form.label :name, class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :name, class: 'form-control'
      .form-group
        = form.label :description, class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :description, class: 'form-control'
      .form-group
        = form.label :level, class: 'col-lg-2 control-label'
        .col-lg-10
          = form.select :level, %w[alto medio baixo], {}, class: 'form-control'
      .form-group
        = form.label :item, class: 'col-lg-2 control-label'
        .col-lg-10
          = form.select 'item_id', current_accountant.items.collect { |item| [ item.name, item.id ] }, {}, class: 'form-control'
      .form-group
        .col-lg-offset-2.col-lg-10
          = form.submit button, class: 'btn btn-outline btn-primary btn-lg'

app/views/subitems/edit.html.haml
= render 'form', subitem: @subitem, method: :put, title: 'ATUALIZAR SUBITEM', button: 'Atualizar'

app/views/subitems/index.html.haml
.row
  .col-lg-12
    %h3.page-header
      %i.fa.fa-laptop
      Subitem
    %ol.breadcrumb{ style: 'background-color: gainsboro;' }
      %li
        %i.fa.fa-home
        %a{href: "/"} Home
      %li= link_to 'Subitem', subitems_path
      %li= link_to 'Criar subitem', new_subitem_path

.row
  .col-lg-12
    %table#table-item.table.table-bordered
      %thead
        %tr{:role => "row"}
          %th
            Nome
          %th.sorting{"aria-controls" => "dataTables-example", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 207px;", :tabindex => "0"}
            Descrição
          %th
            Nível
          %th
            Item
          %th
            Ações
      %tbody
        - @subitems.each do |subitem|
          %tr.gradeA.odd{:role => "row"}
            %td= subitem.name
            %td= subitem.description
            %td= subitem.level
            %td= subitem.item.name
            %td
              = link_to 'Editar', edit_subitem_path(subitem)
              = link_to 'Apagar', subitem, method: :delete, data: { confirm: 'Are you sure?' }

app/views/subitems/new.html.haml
= render 'form', subitem: @subitem, method: :post, title: 'NOVO SUBITEM', button: 'Salvar'

app/views/subitems/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @subitem.name
%p
  %strong Description:
  = @subitem.description
%p
  %strong Level:
  = @subitem.level
%p
  %strong Account type:
  = @subitem.account_type
= link_to 'Edit', edit_subitem_path(@subitem)
|
= link_to 'Back', subitems_path