config/routes.rb
Rails.application.routes.draw do

  root to: 'app#index'

  devise_scope :accountant do
    post '/accountants/sign_in', to: 'accountants/sessions#create'
    get '/accountants/sign_in', to: 'accountants/sessions#new'
    get '/accountants/sign_up', to: 'accountants/registrations#new'
    post '/accountants/', to: 'accountants/registrations#create'
  end


  devise_for :accountants
  # resources :transactions
  resources :subitems
  resources :items
  resources :accounts do
    get :line_chart, on: :collection
  end
  resources :accountants
  resources :debts
  resources :transfers do
    get :pie_chart, on: :collection
  end
  resources :bank_statements, only: [:new, :create]

  resources :reports, only: [] do
    get :line, on: :collection
    get :pie_chart, on: :collection
  end

  get '/reports', to: 'reports#transfers'

  namespace :admins do
    resources :tasks
  end

end

app/models/transfer.rb
# == Schema Information
#
# Table name: transfers
#
#  id                     :bigint(8)        not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  destiny_transaction_id :bigint(8)
#  origin_transaction_id  :bigint(8)
#
# Indexes
#
#  index_transfers_on_destiny_transaction_id  (destiny_transaction_id)
#  index_transfers_on_origin_transaction_id   (origin_transaction_id)
#
# Foreign Keys
#
#  fk_rails_...  (destiny_transaction_id => transactions.id)
#  fk_rails_...  (origin_transaction_id => transactions.id)
#

class Transfer < ApplicationRecord
  extend RuleMap

  belongs_to :origin_transaction, class_name: 'Transaction', foreign_key: :origin_transaction_id, autosave: true
  belongs_to :destiny_transaction, class_name: 'Transaction', foreign_key: :destiny_transaction_id, autosave: true, optional: true

  after_destroy :destroy_transactions

  def destroy_transactions
    origin_transaction = self.origin_transaction
    destiny_transaction = self.destiny_transaction

    origin_transaction.destroy!
    destiny_transaction.destroy! if destiny_transaction
  end

  rules_of_insert [
    Strategy::Transfers::CheckTransactions,
    Strategy::Transfers::CheckAccounts,
    Strategy::Transfers::TransferDataBetweenAccounts,
    Strategy::Transfers::SetOriginTransaction,
    Strategy::SaveEntity,
    Strategy::ClosedMonths::Update,
  ]

  rules_of_list [
    Strategy::Transfers::Filter,
    Strategy::Reports::PieChart,
  ]

  rules_of_destroy [
    Strategy::DestroyEntity,
  ]

  rules_of_update [
    Strategy::Transfers::CheckDisassociate,
    Strategy::Transfers::SetAttributesTransactions,
    Strategy::Transfers::CheckTransactions,
    Strategy::Transfers::CheckAccounts,
    Strategy::Transfers::TransferDataBetweenAccounts,
    Strategy::Transfers::UpdateTransfer,
  ]
end

app/controllers/transfers_controller.rb
class TransfersController < AuthenticateBaseController
  before_action :initialize_variables, only: [:index, :create, :edit, :new, :update]
  before_action :set_transfer, only: [:destroy]
  before_action :set_facade, only: [:index, :create, :update, :destroy, :pie_chart]

  def index
    transaction_all
  end

  def new
    @transaction = Transaction.new
  end

  def edit
    @transaction = Transaction.find_by(id: params[:id])
    @selected_account_id = @transaction.account_id

    associated = @transaction.associated_transaction
    if associated
      @selected_destination_account_id = associated.account.id
    end

    @selected_subitem = @transaction.subitem
    if @selected_subitem
      @selected_item = @selected_subitem.item

      @selected_subitem_id = @selected_subitem.id
      @selected_item_id = @selected_subitem.item_id
    end

  end

  def create
    @origin_transaction = Transaction.new(transaction_params)

    transfer = Transfer.new
    transfer.origin_transaction = @origin_transaction
    if params[:destiny_account_id].present?
      @destiny_transaction = Transaction.new(account_id: params[:destiny_account_id])
      transfer.destiny_transaction = @destiny_transaction
    end

    transporter = @facade.insert(transfer)

    if transporter.status == :green
      @transaction = Transaction.new
      flash[:notice] = 'Transação gravada'
      if params[:commit].include? 'nova'
        redirect_to action: :new
      else
        redirect_to action: :index, filter: filter_from_session, page: page_from_session, per_page: per_page_from_session
      end
    else
      @transaction = @origin_transaction
      @selected_account_id = @origin_transaction.account
      @selected_destination_account_id = @destiny_transaction.account.id if @destiny_transaction
      flash[:error] = transporter.messages
      render :new
    end
    
  end

  def update

    current_transaction = Transaction.find(params[:id])
    @transfer = Transfer.find(params[:transfer_id])

    map = {
        current_transaction: current_transaction,
        attributes_orgin: transaction_params,
    }
    map[:attributes_destiny] = { account_id: params[:destiny_account_id] } if params[:destiny_account_id].present?

    transporter = @facade.update @transfer, map

    if transporter.status == :green
      flash[:notice] = 'Transação atualizada!'
      redirect_to action: :index, filter: filter_from_session, page: page_from_session, per_page: per_page_from_session
    else
      transaction_params.each do |key, value|
        current_transaction[key] = value
      end
      @transaction = current_transaction
      @selected_account_id = @transaction.account_id
      associated = @transaction.associated_transaction
      @selected_destination_account_id = associated.account.id if associated
      flash[:error] = transporter.messages
      render :edit
    end
  end

  def destroy

    transporter = @facade.delete @transfer

    if transporter.status == :green
      flash[:notice] = 'Transação deletada'
      redirect_to action: :index, filter: filter_from_session, page: page_from_session, per_page: per_page_from_session
    else
      flash[:error] = transporter.messages
      render :index
    end
  end

  def pie_chart
    @transporter = @facade.select(:transfer, filter: filter_params || {}, pie_chart: true)
    data = @transporter.bucket[:data]
    @positives = data[:positives]
    @negatives = data[:negatives]
  end

  private

  def initialize_variables

    @selected_account_id = nil
    @selected_destination_account_id = nil
    @array_accounts = [['','']] + current_accountant.accounts.collect { |a| [a.name, a.id] }
    @destination_accounts = @array_accounts

    @errors = []
    @errors << 'Deve existir pelo menos uma conta.' unless current_accountant.accounts.present?
    @errors << 'Deve existir pelo menos um item.' unless current_accountant.items.present?
    @errors << 'Deve existir pelo menos um subitem.' unless current_accountant.subitems.present?

  end

  def transaction_params
    params.require(:transaction).permit(:date_transaction, :price, :description, :title, :amount, :subitem_id, :account_id, :ignore)
  end

  def filter_params
    filter[:start_date] = Date.today.beginning_of_month unless filter[:start_date].present?
    filter[:end_date] = Date.today.end_of_month unless filter[:end_date].present?
    filter
  end

  def set_transfer
    @transfer = Transfer.find(params[:id])
  end

  def transaction_all
    transporter = @facade.select(:transfer, filter: filter_params)
    @transactions = transporter.bucket[:transactions].page(page).per(per_page)
    cookies[:filter] = @filter.to_json
  end

  def set_facade
    @facade ||= Facade.new(current_accountant)
  end

end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_filter.html.haml
.row
  .col-lg-12
    .panel.panel-default
      #div-filter.panel-heading
        %h5.mb-0
          %button.btn.btn-link.collapsed{"aria-controls" => "div-collapse", "aria-expanded" => "false", "data-target" => "#div-collapse", "data-toggle" => "collapse"}
            Filtros
      #div-collapse.panel.panel-body.collapse
        = form_tag url, method: :get do
          .row
            .col-lg-2
              %label Data inicial
            .col-lg-2
              %label Data final
            .col-lg-2
              %label Conta
            .col-lg-2
              %label Item
            .col-lg-2
              %label Subitem
            .col-lg-2
              %lable Ignorados?
          .row
            .col-lg-2
              = text_field_tag 'filter[start_date]', filter[:start_date], type: :date, class: 'form-control'
            .col-lg-2
              = text_field_tag 'filter[end_date]', filter[:end_date], type: :date, class: 'form-control'
            .col-lg-2
              = select_tag 'filter[account_id]', options_for_select_accounts(first_blank: true, selected: filter[:account_id]), class: 'form-control'
            .col-lg-2
              = select_tag 'filter[item_id]', options_for_select_items(first_blank: true, selected: filter[:item_id]), id: :transaction_item_id, class: 'form-control'
            .col-lg-2
              = select_tag 'filter[subitem_id]', options_for_select_subitems(first_blank: true, selected: filter[:subitem_id]), id: :transaction_subitem_id, class: 'form-control'
            .col-lg-2
              = check_box_tag 'filter[ignore]', true, filter[:ignore]
          .row{ style: 'border-top-width: 10px; margin-top: 10px;' }
            .col-lg-10
              = submit_tag 'Buscar', class: 'btn btn-info pull-right', style: 'width: 100%'


= dynamic_select_items_subitems

app/views/transfers/_form.html.haml
%section.panel
  %header.panel-heading
    Horizontal Forms
  .panel-body
    = form_with(model: @transaction, url: url, method: method, local: true, class: 'form-horizontal') do |form|
      - if @transaction.transfer
        = hidden_field_tag :transfer_id, @transaction.transfer.id
      .form-group
        = form.label 'Selecione a conta', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.select(:account_id, options_for_select_accounts(selected: @selected_account_id), {}, { class: 'form-control' })
      .form-group
        = form.label 'Ignorar?', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.check_box :ignore
      .form-group
        = form.label 'Data', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :date_transaction, type: :date, class: 'form-control'
      .form-group
        = form.label 'Valor', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :price, class: 'form-control'
      .form-group
        = form.label 'Quantidade', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :amount, class: 'form-control'
      .form-group
        = form.label 'Descrição', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :description, class: 'form-control'
      .form-group
        = form.label 'Título', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.text_field :title, class: 'form-control'
      .form-group
        = form.label 'Item', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.select(:item_id, options_for_select_items(selected: @selected_item_id), {}, { class: 'form-control' })
      .form-group
        = form.label 'Subitem', class: 'col-lg-2 control-label'
        .col-lg-10
          = form.select(:subitem_id, options_for_select_subitems(selected: @selected_subitem_id), {}, { class: 'form-control' })
      .form-group
        = form.label 'Selecione a conta destino', class: 'col-lg-2 control-label'
        .col-lg-10
          = select_tag(:destiny_account_id, options_for_select_accounts(selected: @selected_destination_account_id, first_blank: true), { class: 'form-control' })
      .form-group
        .col-lg-offset-2.col-lg-10
          = form.submit button, class: 'btn btn-primary'
          - unless params[:action] == 'edit'
            = hidden_field_tag :new_transaction, true
            = form.submit 'Salvar e nova transação', class: 'btn btn-primary'

= dynamic_select_items_subitems

app/views/transfers/_header.html.haml
.row
  .col-lg-12
    %h3.page-header
      %i.fa.fa-laptop
      Transações
    %ol.breadcrumb{ style: 'background-color: gainsboro;' }
      %li
        %i.fa.fa-home
        %a{href: "/"} Home
      %li= link_to 'Transações', transfers_path
      - unless params[:action] == 'new'
        %li= link_to 'Criar nova transação', new_transfer_path

app/views/transfers/_pie_chart.js.erb
var positives = [['Item', 'Valor']]; //JSON.parse('#{@positives.to_json.html_safe}');
var negatives = [['Item', 'Valor']]; //JSON.parse('#{@negatives.to_json.html_safe}');

<% @positives.each do |positive| %>
  positives.push(<%= raw [positive[0], Money.new(positive[1]).to_f] %>)
<% end %>

<% @negatives.each do |negative| %>
  negatives.push(<%= raw [negative[0], Money.new(negative[1]).to_f] %>)
<% end %>

google.charts.load("current", {packages:["corechart"]});
google.charts.setOnLoadCallback(drawChart);
google.charts.setOnLoadCallback(drawChart2);

function drawChart() {
    var data = google.visualization.arrayToDataTable(
        negatives
    );

    var options = {
        title: 'SALDO NEGATIVO',
        is3D: true
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart_negatives'));
    chart.draw(data, options);
}


function drawChart2() {
    var data = google.visualization.arrayToDataTable(
        positives
    );

    var options = {
        title: 'SALDO POSITIVO',
        is3D: true
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart_positives'));
    chart.draw(data, options);
}

app/views/transfers/edit.html.haml
= render 'form', url: transfer_path, method: :put, title: 'ATUALIZAR TRANSAÇÃO', button: 'Atualizar'

app/views/transfers/index.html.haml
= render 'header'

= render 'filter', url: transfers_path


.row
  .col-lg-12
    %table#table-transaction.table.table-bordered
      %thead
        %tr{:role => "row"}
          %th Conta
          %th Tipo
          %th Entrada
          %th Data
          %th Valor
          %th Quantidade
          %th Descrição
          %th Título
          %th item
          %th subitem
          %th Conta associada
          %th
      %tbody
        - @transactions.each do |transaction|
          - transfer = transaction.transfer
          - associated = transaction.associated_transaction
          %tr.gradeA.odd{role: :row, class: transaction.ignore? ? 'disable' : ''}
            %td= transaction.account.name
            %td= transaction.origin? ? 'Origem' : 'Destino'
            %td= transaction.input
            %td= format_date transaction.date_transaction
            %td= transaction.price
            %td= transaction.amount
            %td= transaction.description
            %td= transaction.title
            %td= transaction.subitem.item.name if transaction.subitem
            %td= transaction.subitem.name if transaction.subitem
            %td= associated.account.name if associated
            %td
              = link_to edit_transfer_path(transaction), class: 'btn btn-warning' do
                editar
                %i.fas.fa-edit
              = link_to transfer_path(transfer), method: :delete, style: 'display: inline;', class: 'btn btn-danger', data: { confirm: 'Você tem certeza?' } do
                excluir
                %i.fas.fa-trash-alt

.row.text-center
  = paginate @transactions

:css

  .disable {
    background-color: #e2cecc;
  }

app/views/transfers/new.html.haml
- if @errors.present?

  %section.panel
    %header.panel-heading
      Transação
    .panel-body
      .panel.panel-danger
        .panel-heading Para uma nova transação é nescessário corrigir os erros abaixo
        - @errors.each do |error|
          .panel-content= error
      .panel.panel-info

- else

  = render 'header'

  = render 'form', url: transfers_path, method: :post, title: 'SALVAR TRANSAÇÃO', button: 'Salvar'

app/views/transfers/pie_chart.html.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

= render 'transfers/filter', url: pie_chart_transfers_path

.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        %h5.mb-0
          %button.btn.btn-link.collapsed{"aria-controls" => "div-collapse", "aria-expanded" => "false", "data-target" => "#div-collapse-grafico", "data-toggle" => "collapse"}
            Gráficos
      #div-collapse-grafico.panel.panel-body.collapse.in
        .row
          .col-lg-6
            #piechart_negatives{style: "width: 100%; height: 500px; z-index: -1"}
          .col-lg-6
            #piechart_positives{style: "width: 100%; height: 500px;"}

.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        %h5.mb-0
          %button.btn.btn-link.collapsed{"aria-controls" => "div-collapse", "aria-expanded" => "false", "data-target" => "#div-collapse-table", "data-toggle" => "collapse"}
            Tabelas
      #div-collapse-table.panel.panel-body.collapse.in

        .row
          .col-lg-6
            .alert.alert-danger
              %table.table
                %thead
                  %tr
                    %th Item
                    %th Valor
                %tbody
                  - array = @negatives.clone
                  - total = 0
                  - array.each do |item|
                    - total += item[1]
                    %tr
                      %td= item[0]
                      %td= format_currency item[1]
                %tfoot
                  %tr
                    %th
                      %strong TOTAL
                    %th
                      %strong= format_currency total

          .col-lg-6
            .alert.alert-success
              %table.table
                %thead
                  %tr
                    %th Item
                    %th Valor
                %tbody
                  - array = @positives.clone
                  - total = 0
                  - array.each do |item|
                    - total += item[1]
                    %tr
                      %td= item[0]
                      %td= format_currency item[1]
                %tfoot
                  %tr
                    %th
                      %strong TOTAL
                    %th
                      %strong= format_currency total
%script
  = render partial: 'pie_chart', formats: [:js]