config/routes.rb
Rails.application.routes.draw do

  root to: 'app#index'

  devise_scope :accountant do
    post '/accountants/sign_in', to: 'accountants/sessions#create'
    get '/accountants/sign_in', to: 'accountants/sessions#new'
    get '/accountants/sign_up', to: 'accountants/registrations#new'
    post '/accountants/', to: 'accountants/registrations#create'
  end


  devise_for :accountants
  # resources :transactions
  resources :subitems
  resources :items
  resources :accounts do
    get :line_chart, on: :collection
  end
  resources :accountants
  resources :debts
  resources :transfers do
    get :pie_chart, on: :collection
  end
  resources :bank_statements, only: [:new, :create]

  resources :reports, only: [] do
    get :line, on: :collection
    get :pie_chart, on: :collection
  end

  get '/reports', to: 'reports#transfers'

  namespace :admins do
    resources :tasks
  end

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id                  :bigint(8)        not null, primary key
#  description         :string
#  header_file         :string
#  ignore_descriptions :text             default("")
#  name                :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  accountant_id       :bigint(8)
#
# Indexes
#
#  index_accounts_on_accountant_id  (accountant_id)
#

class Account < ApplicationRecord
  extend RuleMap

  has_many :transactions
  has_many :closed_months
  belongs_to :accountant

  monetize :total_balance_cents


  def total_balance_cents
    last = self.closed_months.try(:last)
    last ? last.price_cents : 0
  end

  def ignores
    list = ignore_descriptions.split ';'
    list.map { |description| description.strip.downcase }
  end

  rules_of_insert [
    Strategy::Accounts::CheckName,
    Strategy::SaveEntity
  ]
  rules_of_update  [
    Strategy::Accounts::CheckName,
    Strategy::SaveEntity
  ]
  rules_of_list [
    Strategy::Accounts::Filter,
    Strategy::Reports::LineChart
  ]
  rules_of_destroy [
    Strategy::Accounts::CheckAssociation,
    Strategy::DestroyEntity
  ]

end

app/controllers/accounts_controller.rb
class AccountsController < AuthenticateBaseController
  before_action :set_account, only: [:edit, :update, :destroy]
  before_action :set_facade, only: [:index, :create, :update, :destroy, :line_chart]

  def index
    account_all
  end

  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.accountant = current_accountant

    transporter = @facade.insert @account, current_accountant

    if transporter.status == :green
      flash[:notice] = 'Conta criado.'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      render :new
    end
  end

  def update

    transporter = @facade.update @account, attributes: account_params

    if transporter.status == :green
      flash[:notice] = 'conta atualizada.'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      render :edit, account: @account
    end
  end

  def destroy
    transporter = @facade.delete @account

    if transporter.status == :green
      flash[:notice] = 'Conta deletada.'
      redirect_to action: :index
    else
      flash[:error] = transporter.messages
      redirect_to action: :index
    end
  end

  def line_chart
    @filter = {}
    @transporter = @facade.select(:account, filter: {}, line_chart: true)
    @data = @transporter.bucket[:data]
    @data
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:name, :description, :header_file, :ignore_descriptions)
  end

  def account_all
    @accounts = Account.where(accountant_id: current_accountant.id)
  end

  def set_facade
    @facade ||= Facade.new(current_accountant)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def options_for_select_header_file(selected=nil, **options)
    array = [
      [t('helpers.account.header_file.date_description_ignore_value'), :date_description_ignore_value],
      [t('helpers.account.header_file.date_description_value'), :date_description_value],
      [t('helpers.account.header_file.ignore_date_doc_description_value_symbol'),:ignore_date_doc_description_value_symbol],
    ]

    array.unshift(['','']) if options[:first_blank]
    options_for_select(array, selected)
  end
end

app/views/accounts/_form.html.haml
.row
  .col-lg-12
    %h3.page-header
      %i.fa.fa-laptop
      Contas
    %ol.breadcrumb{ style: 'background-color: gainsboro;' }
      %li
        %i.fa.fa-home
        %a{href: "/"} Home
      %li
        = link_to 'Contas', accounts_path

%section.panel
  %header.panel-heading
    %h1= title
  .panel-body
    = form_with(model: account, local: true, class: 'form-horizontal') do |form|
      .form-group
        = form.label :name, class: 'col-lg-3 control-label'
        .col-lg-9
          = form.text_field :name, class: 'form-control', placeholder: 'Nome da conta'
      .form-group
        = form.label :description, class: 'col-lg-3 control-label'
        .col-lg-9
          = form.text_field :description, class: 'form-control', placeholder: 'Descrição da conta'
      .form-group
        = form.label :header_file, class: 'col-lg-3 control-label'
        .col-lg-9
          = form.select :header_file, options_for_select_header_file(account.header_file, first_blank: true), {}, class: 'form-control'
      .form-group
        = form.label :ignore_descriptions, class: 'col-lg-3 control-label'
        .col-lg-9
          = form.text_area :ignore_descriptions, class: 'form-control', rezise: :vertical
      .form-group
        .col-lg-offset-2.col-lg-9
          = form.submit button, class: 'btn btn-primary'

app/views/accounts/_line.js.erb
    google.charts.load('current', {'packages':['line']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var header = <%= raw @data.shift %>;

      var data = new google.visualization.DataTable();

      for(var i = 0; i < header.length; i++) {
          if ( i== 0)
            data.addColumn('date', header[i]);
          else
              data.addColumn('number', header[i]);
      }
//      data.addColumn('number', 'Guardians of the Galaxy');
//      data.addColumn('number', 'The Avengers');
//      data.addColumn('number', 'Transformers: Age of Extinction');

      var rows = [];
      <% @data.each do |data| %>
        <% date = data.shift.strftime(('%m/%d/%Y')) %>
        var row = [];
        row.push(new Date('<%= raw date %>'));
        <% data.each do |d| %>
          row.push(<%= raw Money.new(d).to_f %>);
        <% end %>
        rows.push(row);
      <% end %>

      data.addRows(rows);

      var options = {
      chart: {
      title: 'Box Office Earnings in First Two Weeks of Opening',
      subtitle: 'in millions of dollars (USD)'
  },
      width: 900,
      height: 500,
      axes: {
      x: {
      0: {side: 'top'}
  }
  }
  };

      var chart = new google.charts.Line(document.getElementById('line-chart'));

      chart.draw(data, google.charts.Line.convertOptions(options));
  }

app/views/accounts/edit.html.haml
= render 'form', account: @account, method: :put, title: 'ATUALIAZAR CONTA', button: 'Atualizar'

app/views/accounts/index.html.haml
.row
  .col-lg-12
    %h3.page-header
      %i.fa.fa-laptop
      Contas
    %ol.breadcrumb{ style: 'background-color: gainsboro;' }
      %li
        %i.fa.fa-home
        %a{href: "/"} Home
      %li= link_to 'Contas', accounts_path
      %li= link_to 'Criar conta', new_account_path

.row
  .col-lg-12
    %table#table-item.table.table-bordered
      %thead
        %tr{:role => "row"}
          %th
            Nome
          %th
            Descrição
          %th
            Ações
      %tbody
        - @accounts.each do |account|
          %tr.gradeA.odd{:role => "row"}
            %td= account.name
            %td= account.description
            %td
              = link_to 'Editar', edit_account_path(account)
              = link_to 'Apagar', account, method: :delete, data: { confirm: 'Você tem certeza?' }

app/views/accounts/line_chart.html.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

= render 'transfers/filter', url: line_chart_accounts_path

.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        %h5.mb-0
          %button.btn.btn-link.collapsed{"aria-controls" => "div-collapse", "aria-expanded" => "false", "data-target" => "#div-collapse-grafico", "data-toggle" => "collapse"}
            Gráficos
      #div-collapse-grafico.panel.panel-body.collapse.in
        .row
          .col-lg-12
            #line-chart{style: "width: 100%; height: 500px; z-index: -1"}

%script
  = render partial: 'line', formats: [:js]

app/views/accounts/new.html.haml
= render 'form', account: @account, method: :put, title: 'NOVA CONTA', button: 'Salvar'